spring:
  application:
    name: cash-desk-module

  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    default-property-inclusion: non_null

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
  compression:
    enabled: true
    mime-types: application/json,text/plain

cashdesk:
  security:
    api-key-hash: fa82ed811150db64f564c4a0dcc69520d17178cf37703e161a3829018ff8d765
    header-name: FIB-X-AUTH

  idempotency:
    # Time-to-live for cached idempotency responses (in hours)
    # After this time, the same idempotency key can be reused
    ttl-hours: ${CASHDESK_IDEMPOTENCY_TTL_HOURS:24}

  storage:
    # Data directory - stored outside JAR for persistence across deployments
    # Uses ${user.home}/.cashdesk by default, can be overridden with environment variable
    data-dir: ${CASHDESK_DATA_DIR:${user.home}/.cashdesk/data}
    transaction-file: ${cashdesk.storage.data-dir}/transactions.txt
    balance-file: ${cashdesk.storage.data-dir}/balances.txt

  backup:
    # Backup configuration for data protection and disaster recovery
    enabled: ${CASHDESK_BACKUP_ENABLED:true}
    directory: ${CASHDESK_BACKUP_DIR:${user.home}/.cashdesk/backups}
    # Cron expression: Daily at 2 AM (0 0 2 * * *)
    # For testing: every 4 hours (0 0 */4 * * *)
    schedule: ${CASHDESK_BACKUP_SCHEDULE:0 0 2 * * *}
    retention:
      max-backups: 30        # Keep last 30 backups
      max-age-days: 90       # Delete backups older than 90 days
    compression: true        # Compress backups to save space

  cashiers:
    initial-balances:
      bgn:
        amount: 1000.00
        denominations:
          10: 50
          50: 10
      eur:
        amount: 2000.00
        denominations:
          10: 100
          20: 0
          50: 20
    names: MARTINA,PETER,LINDA

logging:
  level:
    com.fibank.cashdesk: INFO
    org.springframework: WARN
    org.springframework.web: WARN
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/cashdesk.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 300MB

management:
  endpoints:
    web:
      exposure:
        # Expose health, info, and metrics endpoints
        # For production, consider limiting to just 'health' and 'info'
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    defaults:
      enabled: true
    diskspace:
      enabled: true
      threshold: 10MB  # Alert if less than 10MB free disk space
